2019-05-20 23:40:32,614 | WARNING | Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /session/f3e531d1fa8df4f70426bb5ba3d42335
2019-05-20 23:40:32,615 | WARNING | Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fed19807d68>: Failed to establish a new connection: [Errno 111] Connection refused',)': /session/f3e531d1fa8df4f70426bb5ba3d42335
2019-05-20 23:40:32,616 | WARNING | Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fed19807ef0>: Failed to establish a new connection: [Errno 111] Connection refused',)': /session/f3e531d1fa8df4f70426bb5ba3d42335
